name = "russ-fm"
compatibility_date = "2024-03-01"
main = "./_worker.js"

# Workers Assets configuration - serves static files from dist-worker
[assets]
directory = "./dist-worker"
binding = "ASSETS"

# Environment variables
[vars]
ENVIRONMENT = "production"

# R2 bucket binding (for your image storage)
# [[r2_buckets]]
# binding = "IMAGES"
# bucket_name = "your-r2-bucket-name"

# Custom domain routing (when ready)
[[routes]]
pattern = "russ.fm/*"
zone_name = "russ.fm"

# Preview environment configuration
[env.preview]
vars = { ENVIRONMENT = "preview" }

# Production environment configuration  
[env.production]
vars = { ENVIRONMENT = "production" }